name: Iris — Diese Woche in DiB
description: "Jeden Sonntag, das Wichtigste aus DEMOKRATIE IN BEWEGUNG in Deiner Inbox!"
link: https://iris.bewegung.jetzt/
source: "."
dest: "build"
rss: "rss.xml"
post_path: "ausgaben/:edition/"

ignore:
  - .git/*
  - build/*
  - .deploy/*
  - generate.py
  - pip-selfcheck.json
  - bin
  - lib
  - include
  - requirements.txt
  - README.md
  - LICENSE
  - examples